name = "codigofacil-site"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Pages-specific configuration
pages_build_output_dir = "out"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]